function createfigure(YMatrix1)
%CREATEFIGURE(YMatrix1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 28-Mar-2023 14:39:55

% Create figure
figure1 = figure('WindowState','maximized');

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',axes1);
set(plot1(1),'DisplayName','Сигнал');
set(plot1(2),'DisplayName','Эрмитов (1-й)');
set(plot1(3),'DisplayName','Эрмитов (2-й)');
set(plot1(4),'DisplayName','Эрмитов (3-1)');
set(plot1(5),'DisplayName','Пуассона (2-й)');
set(plot1(6),'DisplayName','Морле');
set(plot1(7),'DisplayName','Мод. Морле');

% Create title
title({'Сравнение качества обработки вейвлет-преобразований на примере реального сигнала'});

box(axes1,'on');
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'FontSize',18);

